"""
fetch_fonts.py — download self-hosted .woff2 files from Google Fonts.

Hits the Google Fonts CSS2 API with a modern browser UA (forces .woff2 URLs in the
@font-face declarations), then downloads each referenced font file into this
directory and writes a self-contained `fonts.css` next to them.

Run once. Re-run only if you change the FAMILIES list.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from urllib.request import Request, urlopen

HERE = Path(__file__).resolve().parent

# Modern Chrome UA forces the CSS2 API to return woff2 URLs in @font-face rules.
UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"
)

FAMILIES = [
    ("Space Grotesk", "wght@400;500;600;700", "space-grotesk"),
    ("Inter", "wght@400;500;600;700", "inter"),
    ("JetBrains Mono", "wght@400;500", "jetbrains-mono"),
]

UNICODE_RANGES_TO_KEEP = {"latin"}  # skip latin-ext/vietnamese/cyrillic/greek subsets


def fetch(url: str) -> bytes:
    req = Request(url, headers={"User-Agent": UA})
    with urlopen(req, timeout=30) as resp:
        return resp.read()


def main() -> int:
    css_out: list[str] = [
        "/* Self-hosted Followthrough fonts. Generated by fetch_fonts.py. */",
        "",
    ]

    for family, axis, slug in FAMILIES:
        api_url = (
            "https://fonts.googleapis.com/css2"
            f"?family={family.replace(' ', '+')}:{axis}&display=swap"
        )
        print(f"[fetch] {family} :: {api_url}")
        css_text = fetch(api_url).decode("utf-8")

        # Subset comments precede each @font-face block. Pair them by scanning.
        pattern = re.compile(
            r"/\*\s*(?P<subset>[a-z0-9\-]+)\s*\*/\s*(?P<block>@font-face\s*\{[^}]+\})"
        )
        matches = list(pattern.finditer(css_text))
        if not matches:
            print(f"  ! no @font-face blocks parsed for {family}", file=sys.stderr)
            return 1

        kept = 0
        for m in matches:
            subset = m.group("subset")
            block = m.group("block")
            if subset not in UNICODE_RANGES_TO_KEEP:
                continue

            weight_match = re.search(r"font-weight:\s*(\d+);", block)
            url_match = re.search(r"url\((https://[^)]+\.woff2)\)", block)
            range_match = re.search(r"unicode-range:\s*([^;]+);", block)
            if not (weight_match and url_match):
                continue

            weight = weight_match.group(1)
            font_url = url_match.group(1)
            unicode_range = range_match.group(1).strip() if range_match else None

            fname = f"{slug}-{weight}.woff2"
            (HERE / fname).write_bytes(fetch(font_url))
            print(f"  - {fname}  (weight {weight})")

            css_out.append("@font-face {")
            css_out.append(f"  font-family: '{family}';")
            css_out.append("  font-style: normal;")
            css_out.append(f"  font-weight: {weight};")
            css_out.append("  font-display: swap;")
            css_out.append(f"  src: url('{fname}') format('woff2');")
            if unicode_range:
                css_out.append(f"  unicode-range: {unicode_range};")
            css_out.append("}")
            css_out.append("")
            kept += 1

        if kept == 0:
            print(f"  ! 0 latin blocks kept for {family}", file=sys.stderr)
            return 1

    (HERE / "fonts.css").write_text("\n".join(css_out), encoding="utf-8")
    print(f"[done] wrote fonts.css ({(HERE / 'fonts.css').stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
